import asyncio
import argparse
import logging
import os
import json
import textwrap
import sys
from mcp import ClientSession, StdioServerParameters
from mcp.client.stdio import stdio_client

# --- Client-Side Setup ---
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger("promptlab-client")

PROMPTLAB_SERVER_SCRIPT = os.path.abspath("promptlab_server.py")

class Colors:
    HEADER = '\033[95m'
    BLUE = '\033[94m'
    GREEN = '\033[92m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'

def pretty_print_result(data, verbose=False):
    """Prints the final result with enhanced error reporting."""
    if not isinstance(data, dict):
        print(f"{Colors.FAIL}Error: Unexpected response format from server.{Colors.ENDC}\n{data}")
        return

    print(f"\n{Colors.GREEN}{Colors.BOLD}--- PromptLab Analysis ---{Colors.ENDC}")
    print(f"{Colors.HEADER}Original Query:{Colors.ENDC} {data.get('original_query')}")

    if "error" in data:
        print(f"\n{Colors.FAIL}{Colors.BOLD}--- SERVER-SIDE ERROR ---{Colors.ENDC}")
        print("The server encountered an unrecoverable error. Full details below:")
        print(textwrap.indent(data["error"], "  "))
        print(f"{Colors.FAIL}---------------------------{Colors.ENDC}")
        return

    match_info = data.get('prompt_match', {})
    match_status = match_info.get('status', 'unknown')
    
    print(f"{Colors.BLUE}Prompt Match Status:{Colors.ENDC} {match_status}")
    if verbose and match_info.get('reasoning'):
         print(f"{Colors.BLUE}Reasoning:{Colors.ENDC} {match_info.get('reasoning')}")

    if data.get('enhanced'):
        prompt_name = match_info.get('prompt_name', 'an appropriate template')
        print(f"\n{Colors.GREEN}{Colors.BOLD}Enhanced Query (Generated by {prompt_name}):{Colors.ENDC}")
        print("-" * 80)
        print(data.get('final_query'))
        print("-" * 80)
    else:
        print(f"\n{Colors.BLUE}Query was not enhanced.{Colors.ENDC}")

async def main():
    """Main function to launch the server and call a tool."""
    parser = argparse.ArgumentParser(
        description="A client to interact with the PromptLab MCP server.",
        formatter_class=argparse.RawTextHelpFormatter
    )
    
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("query", nargs="?", default=None, help="The user query to process and enhance.")
    group.add_argument("--list", action="store_true", help="List all available prompts from the server.")
    parser.add_argument("--verbose", "-v", action="store_true", help="Enable verbose output.")
    args = parser.parse_args()

    # Use sys.executable to ensure we use the python from the activated venv
    server_params = StdioServerParameters(command=sys.executable, args=[PROMPTLAB_SERVER_SCRIPT])

    try:
        async with stdio_client(server_params) as (read, write):
            logger.info("Client connected to the server process.")
            async with ClientSession(read, write) as session:
                await session.initialize()
                
                if args.list:
                    result = await session.call_tool(name="list_prompts", arguments={})
                else:
                    result = await session.call_tool(name="optimize_query", arguments={"query": args.query})

                if hasattr(result, 'content') and len(result.content) > 0:
                    result_data = json.loads(result.content[0].text)
                    if args.list:
                        print(json.dumps(result_data, indent=2, ensure_ascii=False))
                    else:
                        pretty_print_result(result_data, args.verbose)
                else:
                    print(f"{Colors.FAIL}Server returned no content.{Colors.ENDC}")

    except Exception as e:
        logger.error(f"An error occurred during client execution: {e}", exc_info=True)
        print(f"{Colors.FAIL}A client-side error occurred. Please check the logs.{Colors.ENDC}")

if __name__ == "__main__":
    if not os.path.exists(PROMPTLAB_SERVER_SCRIPT):
        print(f"{Colors.FAIL}Error: Server script '{PROMPTLAB_SERVER_SCRIPT}' not found.{Colors.ENDC}")
        sys.exit(1)
    asyncio.run(main())